Mon, 04 May 2015 18:05:44 scanner.py[line:319] INFO Scanner starts
Mon, 04 May 2015 18:05:45 scanner.py[line:281] INFO Register scanner: connection refused
